name: smartcity
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:

  google_fonts: ^4.0.3
  form_field_validator: ^1.1.0
    # Bloc for state management
  flutter_bloc: ^8.0.1
    # Functional programming things
  equatable: ^2.0.3
    # Service locator
  get_it: ^7.2.0
    # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.5
    # Local cache
  shared_preferences: ^2.0.13
  dartz: ^0.10.1
  flutter:
    sdk: flutter


  google_maps_routes: ^1.1.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.2
  firebase_core: ^2.5.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  location: ^4.4.0
  flutter_map: ^3.1.0
  google_maps_webservice: ^0.0.19
  flutter_screenutil: ^5.6.1
  cloud_functions: ^4.1.1
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/

  uses-material-design: true
