// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0jc0eVMNXjNJgmBoR0690447K7vJPUL0',
    appId: '1:459040096996:web:5b06d167ed3c71acda62f1',
    messagingSenderId: '459040096996',
    projectId: 'smartcity-91034',
    authDomain: 'smartcity-91034.firebaseapp.com',
    storageBucket: 'smartcity-91034.appspot.com',
    measurementId: 'G-6H425R9QP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rSva1Pp62ENyIiiwNW5xAOCn8ElRvRs',
    appId: '1:459040096996:android:367a0857862d8ab2da62f1',
    messagingSenderId: '459040096996',
    projectId: 'smartcity-91034',
    storageBucket: 'smartcity-91034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUpcGfDKPHSXxjwArp0OH-_H7Y5aGtLHo',
    appId: '1:459040096996:ios:abfd6f2f334115c1da62f1',
    messagingSenderId: '459040096996',
    projectId: 'smartcity-91034',
    storageBucket: 'smartcity-91034.appspot.com',
    iosClientId:
        '459040096996-4vfj79qbk5hstasele592r6on9aqb6c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUpcGfDKPHSXxjwArp0OH-_H7Y5aGtLHo',
    appId: '1:459040096996:ios:abfd6f2f334115c1da62f1',
    messagingSenderId: '459040096996',
    projectId: 'smartcity-91034',
    storageBucket: 'smartcity-91034.appspot.com',
    iosClientId:
        '459040096996-4vfj79qbk5hstasele592r6on9aqb6c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcity',
  );
}
